global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 30s
    static_configs:
    - targets: 
      - 'doradi.int.automit.de:9100'
      - '192.168.1.31:9100'
      - 'doradi:9100'
